### PR TITLE
add support for album

### LINKED ISSUE #5: Album name
There is no album name in `ID3.Tag`.
Is this bug or feature? 😅

### PR DESCRIPTION
**Pull request by gen1321**
Closes #5

### CODE REVIEW

**Comment by ndac-todoroki** [comment]
Seems nice! thx!
I'd love it if you edit `README` and `lib/id3.ex`'s documents where the example struct is shown.

**Comment by gen1321** [comment]
Oh sure! forgot about it, i will do it later today

**Comment by gen1321** [comment]
@ndac-todoroki fixed

**Comment by ndac-todoroki** [comment]
spasiba! :heart:

**Pull request merged**
